# CI workflow test
name: Student Management App CI

on:
  push:
    branches:
      - main
      - feature-search
      - feature-css
      - feature-delete
      - feature-count

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify HTML File
        run: test -f index.html

      - name: Verify CSS File
        run: test -f style.css

      - name: Verify JavaScript File
        run: test -f script.js

      - name: Display Success Message
        run: echo "Build and Test Passed Successfully"
